<?php  //[STAMP] 742282b1bd2fc9142bdc07af35acffbb
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Module\UnitHelper;

trait UnitGuyActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
